// SPDX-License-Identifier: MIT
// see https://datatracker.ietf.org/doc/html/draft-miller-ssh-agent
#pragma once

// #define SSH_AGENT_FAILURE 5
// #define SSH_AGENT_SUCCESS 6
#define SSH_AGENTC_REQUEST_IDENTITIES 11
#define SSH_AGENT_IDENTITIES_ANSWER 12
#define SSH_AGENTC_SIGN_REQUEST 13
#define SSH_AGENT_SIGN_RESPONSE 14
// #define SSH_AGENTC_ADD_IDENTITY 17
// #define SSH_AGENTC_REMOVE_IDENTITY 18
// #define SSH_AGENTC_REMOVE_ALL_IDENTITIES 19
// #define SSH_AGENTC_ADD_ID_CONSTRAINED 25
// #define SSH_AGENTC_ADD_SMARTCARD_KEY 20
// #define SSH_AGENTC_REMOVE_SMARTCARD_KEY 21
// #define SSH_AGENTC_LOCK 22
// #define SSH_AGENTC_UNLOCK 23
// #define SSH_AGENTC_ADD_SMARTCARD_KEY_CONSTRAINED 26
// #define SSH_AGENTC_EXTENSION 27
// #define SSH_AGENT_EXTENSION_FAILURE 28

#define SSH_AGENT_RSA_SHA2_256 2
#define SSH_AGENT_RSA_SHA2_512 4
